-- This module is the root of the MilnorConjectureOnSpecialValuesCanonicalLaneLean Lean proof package.
import MilnorConjectureOnSpecialValuesCanonicalLaneLean.Basic
import MilnorConjectureOnSpecialValuesCanonicalLaneLean.SourcePackage
import MilnorConjectureOnSpecialValuesCanonicalLaneLean.SourceDependencies
import MilnorConjectureOnSpecialValuesCanonicalLaneLean.Formalization
import MilnorConjectureOnSpecialValuesCanonicalLaneLean.ReviewerBridge
import MilnorConjectureOnSpecialValuesCanonicalLaneLean.TheoremStatement
import MilnorConjectureOnSpecialValuesCanonicalLaneLean.MathlibObjects
import MilnorConjectureOnSpecialValuesCanonicalLaneLean.AdmissibleClass
import MilnorConjectureOnSpecialValuesCanonicalLaneLean.Projection
import MilnorConjectureOnSpecialValuesCanonicalLaneLean.BridgeLemmas
import MilnorConjectureOnSpecialValuesCanonicalLaneLean.GateLemmas
import MilnorConjectureOnSpecialValuesCanonicalLaneLean.FinalTheorem
import MilnorConjectureOnSpecialValuesCanonicalLaneLean.MathlibStatement
